//
//  BehaviorScheduleRevisionIDProviderV1.swift
//  HabitHonker
//

import Foundation

/// V1 normal revision identity: `rev:v1:<target uuid>:change:<revision uuid>` (Phase 4B).
///
/// The revision UUID comes from the injected generator, once per inserted revision. It is a business
/// identity: never the physical row id, never derived from hashing, and never generated by a model
/// property default. The format is frozen; the enrollment baseline keeps its own 4C key.
struct BehaviorScheduleRevisionIDProviderV1: BehaviorScheduleRevisionIDProviding {
    private let uuidSource: @Sendable () -> UUID

    /// Production uses a fresh random UUID per revision; tests inject fixed values.
    init(uuid: @escaping @Sendable () -> UUID = { UUID() }) {
        self.uuidSource = uuid
    }

    func makeRevisionID(targetID: BehaviorTargetID) -> String {
        Self.changeRevisionID(targetID: targetID, revisionUUID: uuidSource())
    }

    /// The frozen V1 format for an explicit revision UUID. Both UUIDs use the 4C canonical text.
    static func changeRevisionID(targetID: BehaviorTargetID, revisionUUID: UUID) -> String {
        "rev:v1:\(BehaviorLogicalIdentity.canonicalUUIDText(targetID.rawValue)):change:\(BehaviorLogicalIdentity.canonicalUUIDText(revisionUUID))"
    }
}
